import { FlashCard } from './Model/FlashCard'


export const getAllFlashCards = () : FlashCard[]  => {
    return [ 
        {serbianTranslation: "hvala", englishTranslation: "thank you"},
        {serbianTranslation: "mačka", englishTranslation: "cat"},
        {serbianTranslation: "promislio", englishTranslation: "thought"},
        {serbianTranslation: "smijeh", englishTranslation: "laugh"},
        {serbianTranslation: "idite", englishTranslation: "go"},
        {serbianTranslation: "kakve", englishTranslation: "what kind"},
        {serbianTranslation: "probudilo", englishTranslation: "wake up"},
        {serbianTranslation: "svinja", englishTranslation: "pig"},
        {serbianTranslation: "lisica", englishTranslation: "fox"},
        {serbianTranslation: "sestra", englishTranslation: "sister"},
        {serbianTranslation: "brat", englishTranslation: "brother"},
        {serbianTranslation: "mesec", englishTranslation: "moon"},
        {serbianTranslation: "stvori", englishTranslation: "created"},
        {serbianTranslation: "dorucak", englishTranslation: "breakfast"},
        {serbianTranslation: "nebo", englishTranslation: "sky"},
        {serbianTranslation: "ljut", englishTranslation: "angry"},
        {serbianTranslation: "oko", englishTranslation: "eye"},
        {serbianTranslation: "život", englishTranslation: "life"},
        {serbianTranslation: "naručiti", englishTranslation: "place an order"},
        {serbianTranslation: "mogao", englishTranslation: "could"},
        {serbianTranslation: "mesto", englishTranslation: "place"},
        {serbianTranslation: "možete", englishTranslation: "you can"},
        {serbianTranslation: "polako", englishTranslation: "slow down"},
        {serbianTranslation: "razumeti", englishTranslation: "understand"},
        {serbianTranslation: "ručak", englishTranslation: "lunch"},
        {serbianTranslation: "noč", englishTranslation: "night"},
        {serbianTranslation: "sendvič", englishTranslation: "sandwich"},
        {serbianTranslation: "led", englishTranslation: "ice"},
        {serbianTranslation: "kuča", englishTranslation: "home"},
        {serbianTranslation: "levo", englishTranslation: "left"},
        {serbianTranslation: "zemlja", englishTranslation: "earth"},
        {serbianTranslation: "desno", englishTranslation: "right"},
        {serbianTranslation: "lopta", englishTranslation: "ball"},
        {serbianTranslation: "početku", englishTranslation: "beginning"},
        {serbianTranslation: "čarapa", englishTranslation: "sock"},
        {serbianTranslation: "piće", englishTranslation: "drink"},
        {serbianTranslation: "teško", englishTranslation: "hard"},
        {serbianTranslation: "kukuruz", englishTranslation: "corn"},
        {serbianTranslation: "hrane", englishTranslation: "food"},
        {serbianTranslation: "milost", englishTranslation: "grace"},
        {serbianTranslation: "slatko", englishTranslation: "sweet"},
        {serbianTranslation: "kiselo", englishTranslation: "sour"}
      ];
}
